[versions]
quarkus = "3.33.3.3"
jandexPlugin = "2.3.0"
gatlingPlugin = "3.15.1.3"
quarkusCucumber = "1.3.0"
swaggerRequestValidator = "3.0.0"
assertj = "3.27.7"
awaitility = "4.3.0"

[libraries]
quarkus-platform-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
quarkus-cucumber = { module = "io.quarkiverse.cucumber:quarkus-cucumber", version.ref = "quarkusCucumber" }
swagger-request-validator-restassured = { module = "com.atlassian.oai:swagger-request-validator-restassured", version.ref = "swaggerRequestValidator" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }

[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
jandex = { id = "org.kordamp.gradle.jandex", version.ref = "jandexPlugin" }
gatling = { id = "io.gatling.gradle", version.ref = "gatlingPlugin" }
